### ISSUE TITLE
How to integrate with VueJs

### ISSUE THREAD

**Issue by lkmadushan** [nhnent/tui.calendar#81] opened 2018-04-27 12:19 UTC
How do I integrate a Vue component into the calendar schedule view?

**Comment by scottybo** [comment] 2018-04-29 08:05
Would also love to know how to integrate this with vuejs

**Comment by lkmadushan** [comment] 2018-05-07 13:01
@scottybo i needed to mount a Vue component into the calendar event using template option, but unfortunately i couldn't do that. i think we need to pass the element as an argument to the template function to achieve this.

**Comment by dongsik-yoo** [comment] 2018-05-08 01:11
Yes, you might be right.
The constructor of `Calendar` needs a element or element's selector as first parameter.

I have experienced it using React like this.
```js
class CalendarMain extends React.Component {
  constructor() {
    super();

    this.options = {
      defaultView: 'month',
      useCreationPopup: true,
      useDetailPopup: true,
      month: {},
      week: {}
    };
  }
  componentDidMount() {
    this.calendar = this.createCalendarMain();
  }

  componentDidUpdate() {
    this.calendar.render();
  }

  createCalendarMain() {
    return new Calendar('#calendar', this.options);
  }

  render() {
    return (
      <div>
        <div id="calendar" style={{height: '600px'}}></div>
      </div>
    );
  }
}
```

**Comment by dongsik-yoo** [comment] 2018-05-11 08:44
Is there anyone who makes a vue wrapper?

**Comment by lkmadushan** [comment] 2018-05-11 12:12
@dongsik-yoo it would be great if we can add something like below to the core.

```
new Calendar('#calendar', {
    ...
    template: {
        milestone: function(element, schedule) {
            return '<span style="color:red;"><i class="fa fa-flag"></i> ' + schedule.title + '</span>';
        },
})
```

Currently it doesn't pass `element` to template functions. if it can be done calendar will be more flexible for VueJs and ReactJs apps

**Comment by lkmadushan** [comment] 2018-05-11 14:46
@dongsik-yoo yep, only schedule's element would be enough :)

**Comment by lkmadushan** [comment] 2018-05-12 18:31
@dongsik-yoo When do you plan to make a new release with above features? :) I'm planning to use tui calendar for my next project.

**Comment by dongsik-yoo** [comment] 2018-05-14 08:06
@lkmadushan I will be able to offer the schedule elements by event `afterDraw` handler and api `Calendar.getElement()`.

For example,
```js
// event handlers
cal.on({
  'afterDraw': function(e) {
    var schedule = e.schedule;
    var element = cal.getElement(schedule.id, schedule.calendarId);
    // use element for Vue or React
  }
});
``` 

 `tui-calendar` uses a template engine, so can't not directly offer a schedule element at that template function call.

If no problem, I hope that the feature will be included in a new release v1.2.0 on 17th May.

**Comment by dongsik-yoo** [comment] 2018-05-15 01:12
@lkmadushan Please check #109 for your request about the element. It'll be released after QA with v1.2.0, if no problem.

**Comment by lkmadushan** [comment] 2018-05-16 15:39
@dongsik-yoo sorry for late reply. i'm bit busy these days.

I think this would be ok, for different schedules we can check type of it and render corresponding Vue component :)

**Comment by dongsik-yoo** [comment] 2018-05-16 16:12
It's okay. We'll release v1.2.0 tomorrow. We are doing QA.

**Comment by dongsik-yoo** [comment] 2018-05-17 08:04
@lkmadushan Here [v1.2.0](https://github.com/nhnent/tui.calendar/releases/tag/v1.2.0) is.

**Comment by lkmadushan** [comment] 2018-05-17 08:07
@dongsik-yoo Thank you very much!

**Comment by lkmadushan** [comment] 2018-05-23 06:49
@dongsik-yoo i'm getting below error when updating a schedule using creation popup.

Check this out: https://codesandbox.io/s/9j4yn57nnr

```
no-conflict.js:13 Uncaught TypeError: Cannot read property 'id' of undefined
    at ScheduleCreationPopup._onClickSaveSchedule (no-conflict.js:13)
    at eval (no-conflict.js:13)
    at forEachArray (no-conflict.js:13)
    at Object.forEach (no-conflict.js:13)
    at ScheduleCreationPopup._onClick (no-conflict.js:13)
    at HTMLDivElement.handler (no-conflict.js:13)
```

Do yo have you any idea?

**Comment by dongsik-yoo** [comment] 2018-05-23 06:56
It's a bug. I found the cause.
I'll let you know a solution.

**Comment by dongsik-yoo** [comment] 2018-05-23 07:07
@lkmadushan Can you create a new issue for that?

**Comment by lkmadushan** [comment] 2018-05-23 07:56
@dongsik-yoo sure! #122

**Comment by dongsik-yoo** [comment] 2018-05-24 10:45
@lkmadushan Is this issue finished? If it is, please close this issue.
Thank you.

**Closed** 2018-05-24 10:47 UTC
Labels: question

**Comment by luzioluna** [comment] 2018-06-12 15:58
Hello lkmadushan, 
Forgive me, I am a bit fresh at javacsript and it confuses me. I am wondering if you can give me a hint how to start with theming my calendar component with your vue-tuicalendar script. I cant seem to figure out how to overwrite the css properties set in your vui.tuicalendar.js file. I try adding : 
 var theme = {
  "common.backgroundColor": "rgba(255, 255, 255, 0)",
  "month.dayname.fontSize": "16px"
};
Under the component script section and Ive tried a thousand other things with no luck. Can you give me a clue?

**Comment by lkmadushan** [comment] 2018-06-12 16:20
@luzioluna 

Is this what you want? https://codesandbox.io/s/kw1o37l195

Check App.vue

**Comment by luzioluna** [comment] 2018-06-12 16:38
Yes! Thank you! Any chance you are available for tutoring? contact you through your website? ill remove this comment tonight

**Comment by lkmadushan** [comment] 2018-06-12 16:41
@luzioluna For sure. let me know if you need any help. Skype: kalpa.lkm

I think your question will help some else later. So keep it :)

**Comment by luzioluna** [comment] 2018-06-12 16:53
sure. you've already advanced me a great deal on my project with this wrapper and your advice. i will get a hold of you. one last thing. why dont the schedule dates show up in the vue on code pen?

**Comment by lkmadushan** [comment] 2018-06-12 16:57
@luzioluna I think it's because fixed dates. Need to update it to relative dates

**Comment by luzioluna** [comment] 2018-06-12 17:02
thanks, sometimes I ask questions before I look at things, not a good habit.

**Comment by dongsik-yoo** [comment] 2018-07-04 01:30
Hello everyone. There is a new TOAST UI Family. I think it's great grid and helpful for your Vue application.
TOAST UI Grid v3.0 has been released. New design and Tree+Grid. Please have a look. 

https://github.com/nhnent/tui.grid

**Comment by lkmadushan** [comment] 2018-07-04 09:53
@dongsik-yoo that's cool. I will try to create a Vue component for that. Thanks :)

BTW.. I would like to know, is there a timeline view in TUI Calendar?

**Comment by dongsik-yoo** [comment] 2018-07-04 09:59
@lkmadushan Oh, not yet. There are several questions about timeline, but we don't have it yet.
