### ISSUE TITLE
broken column width on Firefox for Windows

### ISSUE THREAD

**Issue by cs09g** [nhnent/tui.calendar#2] opened 2018-02-13 07:44 UTC
Hi,

I've found one bug that the table column width broken while I was testing sample page on Firefox for Windows.

https://nhnent.github.io/tui.calendar/latest/tutorial-example01-basic.html
On the weekly table, if the cell height gets shorter than scrollbar's height from resizing the cell by dragging, scrollbar disappears so the width of the cell seems calculated wrong.

The scrollbar image is resizing for shorter height on Chrome but Firefox doesn't so it's happening I guess.

I've reported that issue on [Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1437787) anyway, it also needs some kind of research to find the way to solve this on client-side.

![image](https://user-images.githubusercontent.com/7428017/36138506-f1ab1c24-10dc-11e8-9cb6-f8757204b848.png)

**Comment by dongsik-yoo** [comment] 2018-02-13 09:10
안녕하세요. @cs09g 
`tui-calendar`에 관심 가져 주셔서 감사합니다.

말씀해 주신 부분이 맥-파이어폭스에서는 발생하지 않는데요, 윈도우-파이어폭스에서 발생하는 거죠?

P.S.
* 이슈 등록할 때 만들어지는 이슈 템플릿에 보시면 OS나 브라우저 정보가 있습니다. 다음에는 같이 기재 부탁 드립니다.
* 해외 사용자를 위하여 이슈 제목을 영어로 바꾸어도 괜찮으실까요?

> Hello @cs09g 
Thank you for your interested in `tui-calendar`.
This issue could be reproduced on Mac-Firefox. Is it on Windows-Firefox?

**Comment by dongsik-yoo** [comment] 2018-02-27 07:17
We've discussed about this. We won't fix it. there are two reasons.
* Because that panel's minimum height will be higher even if no schedule. That panel's minHeight is 20px now. 
* If we have to support this, we'll provide a new api to set minimum height of panel.

In my test, minimum height of panel should be higher than 36px to show scroll bar properly.

**Closed by dongsik-yoo** 2018-02-27 07:17 UTC
Labels: bug
